apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-che-operator
    app.kubernetes.io/part-of: devworkspace-che-operator
  name: devworkspace-che-configmap
  namespace: devworkspace-che
