apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: eclipse-che
  namespace: eclipse-che
spec:
  components: {}
  devEnvironments: {}
  networking:
    tlsSecretName: che-tls
    domain: '{{ .Values.networking.domain }}'
    auth:
      oAuthSecret: '{{ .Values.networking.auth.oAuthSecret }}'
      oAuthClientName: '{{ .Values.networking.auth.oAuthClientName }}'
      identityProviderURL: '{{ .Values.networking.auth.identityProviderURL }}'
  containerRegistry: {}
  gitServices: {}
