apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: che-operator
    app.kubernetes.io/instance: che
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: che
    app.kubernetes.io/part-of: che.eclipse.org
  name: che-operator-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: che-operator
status:
  loadBalancer: {}
